---
kind: Service
apiVersion: v1
metadata:
  name: smb-server-3-19-7
  labels:
    app: smb-server-3-19-7
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: smb-server-3-19-7
  ports:
    - port: 445
      name: smb-server-3-19-7
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-networkdisk-smbshare-3-19-7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-gp3-sc # storage provider is Azure disk in Azure and persistent disk in GCE.
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smb-server-3-19-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server-3-19-7
  template:
    metadata:
      name: smb-server-3-19-7
      labels:
        app: smb-server-3-19-7
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: smb-server-3-19-7
          image: 492804330065.dkr.ecr.us-east-1.amazonaws.com/thuan-ecr/smb:3.19.7
          env:
            - name: PERMISSIONS
              value: "0777"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: password
          args: ["-u", "$(USERNAME);$(PASSWORD)", "-s", "share;/smbshare/;yes;no;no;all;none", "-p"]
          volumeMounts:
            - mountPath: /smbshare
              name: data-volume
          ports:
            - containerPort: 445
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-networkdisk-smbshare-3-19-7