apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-03670cfaa51c41511
    fsType: ext4
    volumeAttributes:
      deviceName: /dev/sdc
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: smb-server-ebs-pv
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-static-sc   # <-- thêm tên StorageClass bất kỳ
#   persistentVolumeReclaimPolicy: Retain
#   csi:
#     driver: ebs.csi.aws.com
#     volumeHandle: vol-05f208b23dc2eddc4
#     fsType: ext4
#     volumeAttributes:
#       deviceName: /dev/xvda