---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-smb
  labels:
    app: bash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bash
  template:
    metadata:
      name: bash
      labels:
        app: bash
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: bash
          image: debian:bullseye-slim
          command:
            - "bash"
            - "-c"
            - "while true; do date -u >> /mnt/smb/data.txt; sleep 1; done"
          volumeMounts:
            - name: smb
              mountPath: "/mnt/smb"
              subPath: subPath
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
